name: Project Pipeline

on:
    push:
      branches:
      - main
      paths:
      - project/**

#  Here, three jobs have been created, and their job_id values are job1_setup_environment, job2_build and job3_test.
jobs:
    job1_setup_environment:
        runs-on: ubuntu-latest
        steps:
            - run: echo The CI/CD is about to begin!
            # Checkout repository
            - name: Checkout
              uses: actions/checkout@v4
              with:
                path: main

            # Install python
            - name: Step#1- Setup Python 3.11
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'

            # Install dependencies
            - name: Step#2- Install dependencies
              run: pip install -r requirements.txt

    job2_build:
        runs-on: ubuntu-latest
        needs: job1_setup_environment

        steps:
            - name: Build python project/pipeline.sh
              run: | 
                echo The Build process about to begin!
                bash project/pipeline.sh
                echo "Build process completed!"

    job3_test:
        runs-on: ubuntu-latest
        needs: [job1_setup_environment, job2_build]

        steps:
            - run: echo The Testing process about to begin!
            - name: Build python project/pipeline.sh
              run: | 
                bash project/tests.sh
                echo "Testing process completed!"